// src/parser/mod.rs
//! Parser entry points and LALRPOP integration.

lalrpop_mod!(
    #[allow(clippy::all)]
    pub grammar,
    "/parser/grammar.rs"
);

pub mod helpers;
mod token_iter;

use token_iter::TokenIter;

use lalrpop_util::ParseError as LalrError;
use crate::ast::arena::AstArena;
use crate::ast::expressions::Expr;
use crate::ast::root::Program;
use crate::error_management::{ErrorManager, error_types::{ParseError, ParseContext}};
use crate::lexer::Token;

/// Parse a full `.ubl` source file into a `Program<'ast>`.
pub fn parse<'ast>(
    arena:  &'ast AstArena,
    tokens: Vec<Token>,
    source: String,
) -> Result<Program<'ast>, ErrorManager> {
    let mut errors = ErrorManager::new(source);
    let iter = TokenIter::new(&tokens);

    match grammar::ProgramParser::new().parse(arena, &mut errors, iter) {
        Ok(program) => {
            if errors.has_errors() { Err(errors) } else { Ok(program) }
        }
        Err(e) => {
            errors.add_parse_error(lalr_to_parse_error(e));
            Err(errors)
        }
    }
}

/// Parse a single expression from a source string using the supplied arena.
///
/// Used by the interpreter to evaluate interpolated string expressions
/// (`$"Hello {some_expr}!"`) at runtime. Returns `None` on lex or parse failure.
///
/// All nodes in the returned `Expr<'ast>` are allocated in `arena` — the
/// local token Vec is consumed and dropped before this function returns.
pub fn parse_expr<'ast>(arena: &'ast AstArena, source: &str) -> Option<&'ast Expr<'ast>> {
    // Tokenize: tokens are consumed eagerly by the iterator; the resulting
    // Expr only references arena memory, so dropping tokens after parse is safe.
    let tokens = crate::lexer::tokenize(source).ok()?;
    let mut errors = ErrorManager::new(source.to_string());
    let iter = TokenIter::new(&tokens);
    // grammar::ExprParser is generated by LALRPOP for the `pub Expr` rule.
    grammar::ExprParser::new().parse(arena, &mut errors, iter).ok()
}

fn lalr_to_parse_error(
    e: LalrError<usize, crate::lexer::TokenType, ParseError>,
) -> ParseError {
    match e {
        LalrError::InvalidToken { location } => ParseError::Raw {
            message: "Invalid token".to_string(),
            span:    crate::lexer::Span::new(location, location, 0, 0),
        },
        LalrError::UnrecognizedEof { location, expected } => ParseError::UnexpectedEof {
            expected,
            span:    crate::lexer::Span::new(location, location, 0, 0),
            context: ParseContext::TopLevel,
        },
        LalrError::UnrecognizedToken { token: (lo, tok, hi), expected } => {
            ParseError::UnexpectedToken {
                found:    tok,
                expected,
                span:     crate::lexer::Span::new(lo, hi, 0, 0),
                context:  ParseContext::TopLevel,
            }
        }
        LalrError::ExtraToken { token: (lo, tok, hi) } => ParseError::UnexpectedToken {
            found:    tok,
            expected: vec![],
            span:     crate::lexer::Span::new(lo, hi, 0, 0),
            context:  ParseContext::TopLevel,
        },
        LalrError::User { error } => error,
    }
            }
